set(LIBRESSL_INCLUDE_DIRECTORIES ${LIBRESSL_INSTALL_DIR}/include)

if (WIN32)
    set(LIBRESSL_CRYPTO_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/crypto.lib)
    set(LIBRESSL_SSL_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/ssl.lib)
    set(LIBRESSL_TLS_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/tls.lib)
    set(LIBRESSL_DEPS "ws2_32;ntdll;bcrypt")
else ()
    set(LIBRESSL_CRYPTO_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/libcrypto.a)
    set(LIBRESSL_SSL_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/libssl.a)
    set(LIBRESSL_TLS_IMPL_LIB_RELEASE ${LIBRESSL_INSTALL_DIR}/lib/libtls.a)
    set(LIBRESSL_DEPS "")
endif ()


if (NOT TARGET LibreSSL::Crypto)
    add_library(LibreSSL::Crypto STATIC IMPORTED)
    set_target_properties(LibreSSL::Crypto
        PROPERTIES
        BUILD_EXTERNAL "On"
        SYSTEM "On"
        INTERFACE_LINK_LIBRARIES "${LIBRESSL_DEPS}"
        BUILD_EXTERNAL_TARGET libressl
        BUILD_EXTERNAL_INTERFACE_INCLUDE_DIRECTORIES "${LIBRESSL_INCLUDE_DIRECTORIES}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_CRYPTO_IMPL_LIB_RELEASE}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_CRYPTO_IMPL_LIB_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_LOCATION_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_LOCATION_DEBUG}"
        MAP_IMPORTED_CONFIG_MINSIZEREL Release
        MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    )
endif ()

if (NOT TARGET LibreSSL::SSL)
    add_library(LibreSSL::SSL STATIC IMPORTED)
    set_target_properties(LibreSSL::SSL
        PROPERTIES
        BUILD_EXTERNAL "On"
        SYSTEM "On"
        INTERFACE_LINK_LIBRARIES "LibreSSL::Crypto"
        BUILD_EXTERNAL_TARGET libressl
        BUILD_EXTERNAL_INTERFACE_INCLUDE_DIRECTORIES "${LIBRESSL_INCLUDE_DIRECTORIES}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_SSL_IMPL_LIB_RELEASE}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_SSL_IMPL_LIB_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_LOCATION_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_LOCATION_DEBUG}"
        MAP_IMPORTED_CONFIG_MINSIZEREL Release
        MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    )
endif ()

if (NOT TARGET LibreSSL::TLS)
    add_library(LibreSSL::TLS STATIC IMPORTED)
    set_target_properties(LibreSSL::TLS
        PROPERTIES
        BUILD_EXTERNAL "On"
        SYSTEM "On"
        INTERFACE_LINK_LIBRARIES "LibreSSL::SSL;LibreSSL::Crypto"
        BUILD_EXTERNAL_TARGET libressl
        BUILD_EXTERNAL_INTERFACE_INCLUDE_DIRECTORIES "${LIBRESSL_INCLUDE_DIRECTORIES}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_TLS_IMPL_LIB_RELEASE}"
        BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_TLS_IMPL_LIB_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_RELEASE "${LIBRESSL_LOCATION_RELEASE}"
        #BUILD_EXTERNAL_IMPORTED_LOCATION_DEBUG "${LIBRESSL_LOCATION_DEBUG}"
        MAP_IMPORTED_CONFIG_MINSIZEREL Release
        MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    )
endif ()
