macro(Build3rdParty)
    include(${cmakerc_SOURCE_DIR}/CMakeRC.cmake)

    if(VIO_USE_SYSTEM_LIBRESSL)
        find_package(LibreSSL REQUIRED)
    else()
        CmDepGetPackageInstallDir(LIBRESSL_INSTALL_DIR libressl ${libressl_VERSION})
        list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMake/FindPackage/libressl)
        Find_Package(libressl REQUIRED)
        CmDepBuildExternalCMake(libressl ${libressl_VERSION} ${libressl_SOURCE_DIR} "" "LibreSSL::Crypto;LibreSSL::SSL;LibreSSL::TLS")
    endif()

    if(NOT VIO_USE_SYSTEM_LIBUV)
        add_subdirectory(${libuv_SOURCE_DIR} "${CMAKE_CURRENT_BINARY_DIR}/libuv_build" SYSTEM)
    endif()

    if(VIO_USE_SYSTEM_ADA)
        find_package(ada REQUIRED)
    else()
        add_subdirectory(${ada_SOURCE_DIR} "${CMAKE_CURRENT_BINARY_DIR}/ada_build" SYSTEM)
    endif()

    if(VIO_USE_SYSTEM_DOCTEST)
        find_package(doctest REQUIRED)
    else()
        add_subdirectory(${doctest_SOURCE_DIR} "${CMAKE_CURRENT_BINARY_DIR}/doctest_build" SYSTEM)
    endif()
endmacro()
