macro(Build3rdParty)
    include(${cmakerc_SOURCE_DIR}/CMakeRC.cmake)

    if (VIO_USE_SYSTEM_LIBRESSL)
        find_package(LibreSSL REQUIRED)
    else ()
        CmDepInstallDir(LIBRESSL_INSTALL_DIR libressl ${libressl_VERSION})
        list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMake/FindPackage/libressl)
        Find_Package(libressl REQUIRED)
        CmDepBuildExternal(libressl ${libressl_VERSION} ${libressl_SOURCE_DIR} "-DLIBRESSL_APPS=OFF;-DLIBRESSL_TESTS=OFF" "LibreSSL::Crypto;LibreSSL::SSL;LibreSSL::TLS")
    endif ()

    if (NOT VIO_USE_SYSTEM_LIBUV)
        set(LIBUV_BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(LIBUV_BUILD_BENCH OFF CACHE BOOL "" FORCE)
        set(LIBUV_BUILD_SHARED OFF CACHE BOOL "" FORCE)
        add_subdirectory(${libuv_SOURCE_DIR} SYSTEM)
    endif ()

    if (VIO_USE_SYSTEM_ADA)
        find_package(ada REQUIRED)
    else ()
        set(ADA_TESTING OFF CACHE BOOL "" FORCE)
        set(ADA_BENCHMARKS OFF CACHE BOOL "" FORCE)
        set(ADA_TOOLS OFF CACHE BOOL "" FORCE)
        add_subdirectory(${ada_SOURCE_DIR} SYSTEM)
    endif ()

    if (VIO_USE_SYSTEM_DOCTEST)
        find_package(doctest REQUIRED)
    else ()
        set(DOCTEST_WITH_TESTS OFF CACHE BOOL "" FORCE)
        set(DOCTEST_NO_INSTALL ON CACHE BOOL "" FORCE)
        add_subdirectory(${doctest_SOURCE_DIR} SYSTEM)
    endif ()
endmacro()
