name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jorgen/vio-ci

jobs:
  docker:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  sanitizers:
    needs: docker
    runs-on: ubuntu-24.04
    container: ghcr.io/jorgen/vio-ci:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: asan
            cc: gcc-14
            cxx: g++-14
            c_flags: -fsanitize=address -fno-omit-frame-pointer
            cxx_flags: -fsanitize=address -fno-omit-frame-pointer
            linker_flags: -fsanitize=address
          - name: tsan
            cc: gcc-14
            cxx: g++-14
            c_flags: -fsanitize=thread -fno-omit-frame-pointer
            cxx_flags: -fsanitize=thread -fno-omit-frame-pointer
            linker_flags: -fsanitize=thread
          - name: ubsan
            cc: gcc-14
            cxx: g++-14
            c_flags: -fsanitize=undefined -fno-omit-frame-pointer -fno-sanitize-recover=all
            cxx_flags: -fsanitize=undefined -fno-omit-frame-pointer -fno-sanitize-recover=all
            linker_flags: -fsanitize=undefined
          - name: msan
            cc: clang-18
            cxx: clang++-18
            c_flags: -fsanitize=memory -fno-omit-frame-pointer -fsanitize-memory-track-origins
            cxx_flags: -fsanitize=memory -fno-omit-frame-pointer -fsanitize-memory-track-origins -stdlib=libc++
            linker_flags: -fsanitize=memory -stdlib=libc++ -lc++abi

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -G Ninja -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_C_FLAGS="${{ matrix.c_flags }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.linker_flags }}"

      - name: Build
        run: cmake --build build

      - name: Test
        run: ./build/test/vio_tests
